import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright config — visual regression.
 *
 * Scope: snapshot the rendered layout of public, protected, and admin
 * pages in both themes and at two viewports. NOT functional/e2e
 * testing (no user journeys, no assertions on behaviour) — just
 * pixel-diff against committed baselines.
 *
 * Browser: chromium only. Firefox/WebKit add variance without catching
 * different regressions in this codebase.
 *
 * Baselines live in tests/visual/__screenshots__/ and are committed to git.
 * Regenerate after an intentional visual change with:
 *   pnpm test:visual:update
 *
 * Phase 0.4 of the UI/UX roadmap added auth-bearing projects:
 *   user-state  → /checkout, /orders, /account
 *   admin-state → /admin/* (every page in the tree)
 * These re-use storageState files generated by playwright.setup.ts.
 *
 * Total snapshots after Phase 0.4:
 *   7 public pages × 2 themes × 2 viewports = 28  (pre-existing)
 *   3 user pages   × 2 themes × 2 viewports = 12
 *   N admin pages  × 2 themes × 1 viewport  = ~14  (admin desktop-only)
 *   ─────
 *   54+ baselines
 */
export default defineConfig({
  testDir: './tests/visual',

  /* Phase 0.4 — global setup mints Firebase custom tokens for two
   * test UIDs and persists their signed-in state to tests/.auth/.
   * The auth-bearing projects below consume those state files. */
  globalSetup: './playwright.setup.ts',

  /* Fail the build on any test.only() left behind. */
  forbidOnly: !!process.env.CI,

  /* CI is prone to flakes from cold-start compilation — one retry helps. */
  retries: process.env.CI ? 1 : 0,

  /* One worker — visual regression hates parallelism-induced timing variance. */
  workers: 1,

  /* Quiet reporter locally, GitHub-Actions-friendly on CI. */
  reporter: process.env.CI
    ? [['github'], ['html', { open: 'never', outputFolder: 'playwright-report' }]]
    : [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]],

  /* Shared fixtures per test. */
  use: {
    baseURL: 'http://localhost:5173',

    /* Record a trace for any failing test — makes debugging failures painless. */
    trace: 'retain-on-failure',

    /* Leave screenshots+videos to the visual.spec — don't double-capture. */
    screenshot: 'off',
    video:      'off',
  },

  /* Snapshot tolerance — tuned to catch real regressions, not anti-alias jitter. */
  expect: {
    // Give toHaveScreenshot more time to find two stable consecutive frames.
    // Default is 5000ms, which is tight for a Firebase-backed app with images.
    timeout: 15_000,
    toHaveScreenshot: {
      /* Max fraction of pixels allowed to differ (0.002 = 0.2%). */
      maxDiffPixelRatio: 0.002,
      /* Per-pixel RGB delta before that pixel counts as "different". */
      threshold: 0.15,
      /* Wait for layout to settle before each comparison. */
      animations: 'disabled',
    },
  },

  projects: [
    {
      name: 'desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1440, height: 900 },
        /* Pin the device-pixel-ratio so high-DPI CI vs laptop doesn't diff. */
        deviceScaleFactor: 1,
      },
    },
    {
      name: 'mobile',
      use: {
        ...devices['iPhone 14 Pro'],
        /* Reset viewport explicitly in case device defaults change between
           Playwright versions. */
        viewport: { width: 390, height: 844 },
        deviceScaleFactor: 1,
      },
    },
    /* ── Phase 0.4 ──────────────────────────────────────────────────
     * Auth-bearing projects. Each loads a pre-signed-in storageState
     * generated by playwright.setup.ts. Tests in these projects run
     * specs from tests/visual/protected/ and tests/visual/admin/
     * (filtered via testMatch) so a single spec file isn't accidentally
     * exercised by both an auth and non-auth project.
     */
    {
      name: 'user-state',
      testMatch: /protected\/.*\.spec\.ts$/,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1440, height: 900 },
        deviceScaleFactor: 1,
        storageState: 'tests/.auth/user.json',
      },
    },
    {
      name: 'user-state-mobile',
      testMatch: /protected\/.*\.spec\.ts$/,
      use: {
        ...devices['iPhone 14 Pro'],
        viewport: { width: 390, height: 844 },
        deviceScaleFactor: 1,
        storageState: 'tests/.auth/user.json',
      },
    },
    {
      /* Admin pages are desktop-only by design — the admin UI isn't
       * mobile-optimized and tracking mobile baselines for it would
       * be high churn for low value. */
      name: 'admin-state',
      testMatch: /admin\/.*\.spec\.ts$/,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1440, height: 900 },
        deviceScaleFactor: 1,
        storageState: 'tests/.auth/admin.json',
      },
    },
  ],

  /* Auto-start the dev server for each test run. */
  webServer: {
    command: 'npm run dev',       // ← change this line
    url: 'http://localhost:5173',
    reuseExistingServer: !process.env.CI,
    /* Vite is fast but cold boot + Firebase init takes a moment. */
    timeout: 120_000,
  },
});
