/**
 * inventoryItem.schema.ts — Zod contracts for /inventory_items.
 *
 * Items are the units of stock inside non-tea categories: bottles
 * of milk, bags of beans, jugs of syrup. Each item belongs to one
 * category (FK: categoryId → /inventory_categories/{id}) and tracks
 * a numeric quantity plus a server-derived status.
 *
 * Status derivation (in onInventoryItemWrite, mirrors tea's
 * getInventoryStatus but parameterized on threshold):
 *
 *   quantity === 0                              → out_of_stock
 *   0 < quantity < effectiveThreshold           → low_stock
 *   quantity >= effectiveThreshold              → in_stock
 *
 *   effectiveThreshold = max(item.lowThreshold, category.lowThreshold ?? 3)
 *     — the category is the floor; an item can only raise it.
 *
 * Items NEVER project to /teas/{id} or anywhere customer-facing.
 * They are strictly back-of-house.
 */

import { z } from 'zod';
import { inventoryStatusSchema, type InventoryStatus } from './inventory.schema';
import { deriveItemStatus } from '../../../../functions/src/lib/inventoryStatus';

export { DEFAULT_LOW_THRESHOLD, effectiveLowThreshold } from '../../../../functions/src/lib/inventoryStatus';

/* -------------------------------------------------------------------------- */
/*                              ITEM SCHEMA                                   */
/* -------------------------------------------------------------------------- */

export const inventoryItemSchema = z.object({
  /** Path segment. Auto-generated by the setInventoryItem callable. */
  id:           z.string(),
  /** Parent category. Never 'tea' — tea uses /inventory/{teaId}. */
  categoryId:   z.string().min(1, 'Category is required'),
  name:         z.string().min(2, 'Item name must be at least 2 characters').max(60),
  /** Optional image URL. Reuses the storefront /tea-images bucket
   *  convention but lives at a separate path (storage rules permit
   *  admin writes only). */
  image:        z.string().nullable().optional(),
  /** Per-item override of category.unit. null/undefined = use
   *  category default. */
  unit:         z.string().min(1).max(20).nullable().optional(),
  /** Current stock. Non-negative. Floats are allowed (5.25 kg). */
  quantity:     z.number().nonnegative(),
  /** Per-item override of category.lowThreshold. */
  lowThreshold: z.number().nonnegative().nullable().optional(),
  /** Server-derived. Trigger writes; clients never set. */
  status:       inventoryStatusSchema,
  updatedBy:    z.string(),
  updatedAt:    z.date(),
  /** Soft-delete. Items with isActive=false stay readable so audit
   *  rows linking to them keep resolving, but they don't appear in
   *  the dashboard's item list. */
  isActive:     z.boolean(),
});

export type InventoryItem = z.infer<typeof inventoryItemSchema>;

/* -------------------------------------------------------------------------- */
/*                      UPDATE INPUT (CLIENT-WRITABLE)                        */
/* -------------------------------------------------------------------------- */

/** What an employee/admin can write directly to an item doc. Mirrors
 *  the firestore.rules `inventoryItemClientWriteAllowed` field set. */
export const updateInventoryItemSchema = z.object({
  quantity:  z.number().nonnegative(),
  updatedBy: z.string(),
});

export type UpdateInventoryItemInput = z.infer<typeof updateInventoryItemSchema>;

/* -------------------------------------------------------------------------- */
/*                  SET (CREATE/UPDATE VIA CALLABLE)                          */
/* -------------------------------------------------------------------------- */

export const setInventoryItemInputSchema = z.object({
  id:           z.string().optional(),
  categoryId:   z.string().min(1),
  name:         z.string().min(2).max(60),
  image:        z.string().nullable().optional(),
  unit:         z.string().min(1).max(20).nullable().optional(),
  /** Initial quantity at create. On update, this lets the admin set
   *  the quantity from the item form (alternative to the inline
   *  stepper). */
  quantity:     z.number().nonnegative(),
  lowThreshold: z.number().nonnegative().nullable().optional(),
});

export type SetInventoryItemInput = z.infer<typeof setInventoryItemInputSchema>;

/* -------------------------------------------------------------------------- */
/*                          STATUS HELPER                                     */
/* -------------------------------------------------------------------------- */

/** Single source of truth for quantity → status mapping. Used by
 *  the client (optimistic UI) and the server trigger.
 *
 *  Pass the effective threshold (item override or category default
 *  or DEFAULT_LOW_THRESHOLD). */
export function getItemStatus(quantity: number, threshold: number): InventoryStatus {
  return deriveItemStatus(quantity, threshold);
}
