#!/usr/bin/env node
/**
 * oklch-derive.mjs — Phase 1.1 of the UI/UX roadmap
 *
 * Converts the project's existing hex-based private color ladders
 * (--_ink-*, --_cream-*, --_gold-*, --_steel-*) into perceptually-
 * uniform OKLCH equivalents. Outputs CSS-ready strings that you
 * paste into tokens.css.
 *
 * Why OKLCH:
 *   sRGB hex is non-uniform — #888 isn't perceptually halfway between
 *   black and white; midtones bunch up. OKLCH (Oklab + chroma + hue)
 *   IS uniform: tweaking lightness by 0.05 produces a visually equal
 *   step everywhere on the wheel. The non-obvious payoff is automated
 *   palette generation: the gold-200 → gold-800 ladder can be
 *   re-derived from a single base hue + chroma + lightness ladder
 *   without eyeballing every step.
 *
 * Strategy:
 *   1. Convert every existing hex to OKLCH (preserves visual identity).
 *   2. Round to a sensible precision (L: 0.5%, C: 0.001, H: 0.5°).
 *   3. Print as `<hex> /* fallback *\u002F  oklch(L% C H);` pairs
 *      so the cascade falls through to hex on browsers that don't
 *      support OKLCH (rare in 2026, but ~3% of users worldwide).
 *
 * Usage:
 *   node scripts/oklch-derive.mjs                    print everything
 *   node scripts/oklch-derive.mjs --hex '#b8924a'    convert a single hex
 *
 * Verification:
 *   The conversion is mathematically exact. Visual regression should
 *   show ZERO diffs on browsers with OKLCH support; pre-OKLCH browsers
 *   continue to render the original hex. The point of the migration
 *   isn't to change the look — it's to put us on a uniform space so
 *   future palette tweaks are predictable.
 */
import { converter, formatHex } from 'culori';

const args = process.argv.slice(2);
const idx = args.indexOf('--hex');
const SINGLE = idx >= 0 ? args[idx + 1] : null;

const oklch = converter('oklch');

/* The full primitive ladder — copied from tokens.css. Source-of-truth
 * lives there; this script's job is to print the OKLCH derivations
 * so a developer can paste them in. */
const PALETTES = {
  ink: {
    900: '#090e12',
    800: '#0f1c26',
    700: '#1e3040',
    600: '#253848',
    500: '#2e4458',
    400: '#3a5468',
  },
  steel: {
    400: '#4a7a9b',
    300: '#6a9ab8',
    200: '#8ab8d8',
  },
  cream: {
     50: '#fdfaf5',
    100: '#f8f4ec',
    200: '#f0e8d8',
    300: '#e4d8c4',
    400: '#d0c0a8',
  },
  gold: {
    200: '#e8d490',
    300: '#d4c080',
    400: '#c8aa60',
    500: '#b8924a',
    600: '#a07838',
    700: '#8c6830',
    800: '#7a5828',
  },
};

/** Format an OKLCH triple as a CSS function string. Rounding chosen so
 * the printed value round-trips back through hex within 1 sRGB unit
 * — the visual diff on a screen is below the threshold of perception. */
function fmt(c) {
  if (!c) return 'oklch(0 0 0)';
  const L = (c.l * 100).toFixed(2).replace(/\.?0+$/, '');     // 0.6404 → "64.04"
  const C = c.c.toFixed(4).replace(/\.?0+$/, '');             // 0.0985 → "0.0985"
  const H = (c.h ?? 0).toFixed(2).replace(/\.?0+$/, '');      // 75.32  → "75.32"
  return `oklch(${L}% ${C} ${H})`;
}

function deriveOne(hex) {
  const c = oklch(hex);
  const back = formatHex(c);   // round-trip — should match the input
  const driftWarning = back.toLowerCase() !== hex.toLowerCase()
    ? ` /* round-trip ${back} ≠ ${hex} (sub-pixel drift) */`
    : '';
  return { oklch: fmt(c), driftWarning };
}

if (SINGLE) {
  const { oklch, driftWarning } = deriveOne(SINGLE);
  console.log(`${SINGLE} → ${oklch}${driftWarning}`);
  process.exit(0);
}

// Print the entire ladder formatted for paste into tokens.css.
console.log('/* OKLCH derivations — generated by scripts/oklch-derive.mjs');
console.log(' * Each line: hex first (sRGB fallback), OKLCH second (override). */\n');

for (const [name, ladder] of Object.entries(PALETTES)) {
  console.log(`  /* ── _${name}-* ─────────────────────────── */`);
  for (const [step, hex] of Object.entries(ladder)) {
    const tokenName = `--_${name}-${step}`;
    const { oklch, driftWarning } = deriveOne(hex);
    const pad = ' '.repeat(Math.max(1, 18 - tokenName.length));
    console.log(`  ${tokenName}:${pad}${hex};`);
    console.log(`  ${tokenName}:${pad}${oklch};${driftWarning}`);
  }
  console.log();
}
