/**
 * notificationKeys.test.ts — pin the deterministic ID generators.
 *
 * Notification doc IDs are written by Cloud Functions and read by the
 * client. If the key format changes between writer and reader, every
 * notification breaks. These tests pin the format so an accidental
 * rename surfaces in CI before deploy.
 *
 * The cloud function side has its own copy at functions/src/notificationKeys.ts
 * (vendored due to tsconfig rootDir constraint). The two files MUST
 * stay in sync — confirmed by running `diff` on the two paths.
 */
import { describe, test, expect } from 'vitest';
import {
  keyForOrderStatus,
  keyForCreditEarned,
  keyForSignup,
  keyForWelcomeBonus,
  keyForCreditAdminAdjust,
  isWellFormedKey,
  orderIdOf,
  userIdOf,
  txIdOf,
} from '@/lib/notificationKeys';

describe('keyForOrderStatus', () => {
  test('format matches `order_<id>_<status>_<audience>`', () => {
    expect(keyForOrderStatus(orderIdOf('ELE-2604-A1B2C3'), 'in_progress', 'user'))
      .toBe('order_ELE-2604-A1B2C3_in_progress_user');
    expect(keyForOrderStatus(orderIdOf('ELE-2604-A1B2C3'), 'pending', 'admin'))
      .toBe('order_ELE-2604-A1B2C3_pending_admin');
  });

  test('every order status produces a distinct key for the same order', () => {
    const id = orderIdOf('ELE-2604-A1B2C3');
    const keys = new Set([
      keyForOrderStatus(id, 'pending',          'admin'),
      keyForOrderStatus(id, 'in_progress',      'user'),
      keyForOrderStatus(id, 'in_progress',      'admin'),
      keyForOrderStatus(id, 'ready_for_pickup', 'user'),
      keyForOrderStatus(id, 'shipped',          'user'),
      keyForOrderStatus(id, 'delivered',        'user'),
      keyForOrderStatus(id, 'rejected',         'user'),
      keyForOrderStatus(id, 'cancelled',        'user'),
      keyForOrderStatus(id, 'expired',          'user'),
    ]);
    // 9 distinct (order, status, audience) tuples → 9 distinct keys.
    expect(keys.size).toBe(9);
  });

  test('user vs admin audience produces different keys', () => {
    const id = orderIdOf('ELE-2604-A1B2C3');
    expect(keyForOrderStatus(id, 'in_progress', 'user'))
      .not.toBe(keyForOrderStatus(id, 'in_progress', 'admin'));
  });

  test('deterministic — same inputs always produce same output', () => {
    const id = orderIdOf('ELE-2604-A1B2C3');
    expect(keyForOrderStatus(id, 'in_progress', 'user'))
      .toBe(keyForOrderStatus(id, 'in_progress', 'user'));
  });
});

describe('keyForCreditEarned', () => {
  test('format matches `order_<id>_credit_earned`', () => {
    expect(keyForCreditEarned(orderIdOf('ELE-2604-A1B2C3')))
      .toBe('order_ELE-2604-A1B2C3_credit_earned');
  });

  test('does not collide with delivered notification key', () => {
    const id = orderIdOf('ELE-2604-A1B2C3');
    expect(keyForCreditEarned(id)).not.toBe(keyForOrderStatus(id, 'delivered', 'user'));
  });
});

describe('keyForSignup', () => {
  test('format matches `signup_<uid>`', () => {
    expect(keyForSignup(userIdOf('abc123'))).toBe('signup_abc123');
  });

  test('different users produce different keys', () => {
    expect(keyForSignup(userIdOf('a'))).not.toBe(keyForSignup(userIdOf('b')));
  });
});

describe('keyForWelcomeBonus', () => {
  test('format matches `welcome_<uid>`', () => {
    expect(keyForWelcomeBonus(userIdOf('abc123'))).toBe('welcome_abc123');
  });

  test('does not collide with signup notification for same user', () => {
    const uid = userIdOf('abc123');
    expect(keyForWelcomeBonus(uid)).not.toBe(keyForSignup(uid));
  });
});

describe('keyForCreditAdminAdjust', () => {
  test('format matches `credit_<txId>`', () => {
    expect(keyForCreditAdminAdjust(txIdOf('xyz789'))).toBe('credit_xyz789');
  });
});

describe('isWellFormedKey', () => {
  test('accepts keys generated by all helpers', () => {
    expect(isWellFormedKey(keyForOrderStatus(orderIdOf('ELE-2604-A1B2C3'), 'in_progress', 'user'))).toBe(true);
    expect(isWellFormedKey(keyForCreditEarned(orderIdOf('ELE-2604-A1B2C3')))).toBe(true);
    expect(isWellFormedKey(keyForSignup(userIdOf('abc')))).toBe(true);
    expect(isWellFormedKey(keyForWelcomeBonus(userIdOf('abc')))).toBe(true);
    expect(isWellFormedKey(keyForCreditAdminAdjust(txIdOf('xyz')))).toBe(true);
  });

  test('rejects empty / too-long / wrong-prefix', () => {
    expect(isWellFormedKey('')).toBe(false);
    expect(isWellFormedKey('x'.repeat(201))).toBe(false);
    expect(isWellFormedKey('foo_bar')).toBe(false);
    expect(isWellFormedKey('order with spaces_123')).toBe(false);
    expect(isWellFormedKey('order_with/slash')).toBe(false);
    expect(isWellFormedKey('order_with"quote')).toBe(false);
  });

  test('accepts the legacy auto-generated 20-char Firestore doc IDs as INVALID', () => {
    // Auto-generated IDs (e.g. fJk3lPqRtY7BvNxA1cD2) don't have our
    // structured prefix, so the validator should reject them — good,
    // because that means an unprefixed ID slipping through to the
    // .set() call would be caught by tooling that uses isWellFormedKey.
    expect(isWellFormedKey('fJk3lPqRtY7BvNxA1cD2')).toBe(false);
  });
});
